Task/Task/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Task.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^reports/', include('reports.urls', namespace="reports")),
)

Task/reports/urls.py
from django.conf.urls import patterns, url

from reports import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^list/$', views.ListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<reports_id>\d+)/browsed/$', views.browsed, name='browsed'),
)

Task/reports/models.py
from django.db import models
import datetime
from django.utils import timezone

class Reports(models.Model):
    title = models.TextField()
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.title
    def was_published_recently(self):
    	now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Text(models.Model):
    reports = models.ForeignKey(Reports)
    reports_text = models.CharField(max_length=350)
    browsed = models.IntegerField(default=0)
    def __unicode__(self):
        return self.reports_text

Task/reports/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from reports.models import Reports, Text

class IndexView(generic.TemplateView):
    template_name = 'reports/index.html'
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        reports_list = Reports.objects.order_by('?')[:5]
        context['reports_list'] = reports_list
        return context


class ListView(generic.ListView):
    model = Reports
    template_name = 'reports/list.html'
    """
    def get_queryset(self):
        return Reports.objects.filter(pub_date__lte=timezone.now())[:10]
    """
    """
    def listing(request):
        reports_list = Reports.objects.all()
        paginator = Paginator(reports_list, 10)

        page = request.GET.get('page')
        try:
            reports = paginator.page(page)
        except PageNotAnInteger:
            reports = paginator.page(1)
        except EmptyPage:
            reports = paginator.page(paginator.num_pages)

        return render_to_response('list.html', {"reports": reports})
    """
    context_object_name = "reports_list"    #default is object_list as well as model's_verbose_name_list and/or model's_verbose_name_plural_list, if defined in the model's inner Meta class
    paginate_by = 10




class DetailView(generic.DetailView):
    model = Reports
    template_name = 'reports/detail.html'
    def get_queryset(self):
        """
       # Excludes any reports that aren't published yet.
        """
        return Reports.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Reports
    template_name = 'reports/results.html'

def browsed(request, reports_id):
    p = get_object_or_404(Reports, pk=reports_id)
    try:
        selected_text = p.text_set.get(pk=request.POST['text'])
    except (KeyError, Text.DoesNotExist):
        # Redisplay form.
        return render(request, 'reports/detail.html', {
            'reports': p,
            'error_message': "You didn't select a Report.",
        })
    else:
        selected_text.browsed += 1
        selected_text.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('reports:results', args=(p.id,)))

Task/reports/templates/reports/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'reports/style.css' %}" />

<h1>{{ reports.title }}</h1>   

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reports:browsed' reports.id %}" method="post">
{% csrf_token %}
{% for text in reports.text_set.all %}
    <input type="radio" name="text" id="text{{ forloop.counter }}" value="{{ text.id }}" />
    <label for="text{{ forloop.counter }}">{{ text.reports_text }}</label><br />
{% endfor %}
<input type="submit" value="View statistic" />
</form>

<a href="{% url 'reports:index' %}">Назад</a>

Task/reports/templates/reports/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'reports/style.css' %}" />

{% if reports_list %}
    <ul>
    {% for reports in reports_list %}
        <li><a href="{% url 'reports:detail' reports.id %}">{{ reports.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No reports are available.</p>
{% endif %}
<a href="{% url 'reports:list' %}">Список статей</a>

Task/reports/templates/reports/list.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'reports/style.css' %}" />

{% if reports_list %}
     <ul>
    {% for reports in reports_list %}
        <li><a href="{% url 'reports:detail' reports.id %}">{{ reports.title }}</a></li>
    {% endfor %}
    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/reports/list/?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/reports/list/?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
 </ul>

{% else %}
    <p>No reports are available.</p>
{% endif %}

<a href="{% url 'reports:index' %}">Главная</a>

Task/reports/templates/reports/results.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'reports/style.css' %}" />

<h1>{{ reports.title }}</h1>

<ul>
{% for text in reports.text_set.all %}
    <li>{{ text.reports_text }} -- {{ text.browsed }} browsed{{ text.browsed|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'reports:detail' reports.id %}">Look back</a>